from django.urls import path
from . import views


urlpatterns = [
    #path('home/', views.home, name='home'),
    path('', views.say_hello, name='say_hello'),
    path('studyabroad/', views.studyabroad, name='studyabroad'),
    path('recruiters/', views.recruiters, name='recruiters'),
    path('schools/', views.schools, name='schools'),
    path('new_associate/', views.new_associate, name='new_associate'),
    path('account/', views.account, name='account'),
    path('register/', views.register, name='register'),
    path('story/', views.story, name='story'),
    path('careers/', views.careers, name='careers'),
    path('blog/', views.blog, name='blog'),
    path('press/', views.press, name='press'),
    path('life/', views.life, name='life'),
    path('leadership/', views.leadership, name='leadership'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('fees/', views.fees, name='fees'),
    path('statement/', views.statement, name='statement'),
    path('ielts-writing/', views.ieltswriting, name='ielts-writing'),
    path('affordablecities/', views.affordablecities, name='affordablecities'),
    path('our-solutions/', views.oursolutions, name='oursolutions'),
    path('study-in-uk/', views.studyinuk, name='studyinuk'),
    path('why-admission-platform/', views.whyadmissionplatform, name='whyadmissionplatform'),
    path('mission-vision/', views.missionvision, name='missionvision'),
    path('our-value/', views.ourvalue, name='ourvalue'),
    path('global-recognition/', views.globalrecognition, name='globalrecognition'),
    path('events/', views.events, name='events'),
    path('australia/', views.australia, name='australia'),
    path('canada/', views.canada, name='canada'),
    path('newzealand/', views.newzealand, name='newzealand'),
    path('unitedkingdom/', views.unitedkingdom, name='unitedkingdom'),
    path('unitedstates/', views.unitedstates, name='unitedstates'),
    path('team/', views.team, name='team'),
    path('form-success/', views.form_success, name='form_success'),
    path('australia-partners/', views.australiapartner, name='australiapartner'),
    path('canada-partners/', views.canadapartner, name='canadapartner'),
    path('nz-partners/', views.nzpartner, name='nzpartner'),
    path('uk-partners/', views.ukpartner, name='ukpartner'),
    path('usa-partners/', views.usapartner, name='usapartner'),
    path('find-high-job/', views.findhighjob, name='findhighjob'),
    path('why-australia/', views.whyaustralia, name='whyaustralia'),
    path('why-canada/', views.whycanada, name='whycanada'),
    path('why-newzealand/', views.whynewzealand, name='whynewzealand'),
    path('why-uk/', views.whyuk, name='whyuk'),
    path('why-usa/', views.whyusa, name='whyusa'),
    path('australia-resources/', views.australiaresources, name='australiaresources'),
]