# Generated by Django 5.0.3 on 2024-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination_country", models.CharField(max_length=100)),
                ("school_name", models.CharField(max_length=255)),
                ("contact_first_name", models.CharField(max_length=255)),
                ("contact_last_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contact_title", models.CharField(max_length=255)),
                ("referral_check", models.BooleanField(default=False)),
                ("additional_comments", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
